from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol

from open_publisher_runtime.domain.entities import (
    Article,
    ArticleRevision,
    Artifact,
    ConnectionProfile,
    PlatformVariant,
    PublishAttempt,
    PublishJob,
    PublishPlan,
    PublishReceipt,
    RuntimeEvent,
    Workflow,
    WorkflowRun,
)
from open_publisher_runtime.domain.enums import PublishJobState, RunStatus


class ArtifactBlobStore(Protocol):
    def put(self, content_hash: str, data: bytes) -> str: ...

    def get(self, storage_path: str) -> bytes: ...

    def exists(self, storage_path: str) -> bool: ...


class RuntimeRepository(Protocol):
    def add_article(self, article: Article) -> Article: ...

    def update_article(self, article: Article) -> Article: ...

    def get_article(self, article_id: str) -> Article | None: ...

    def list_articles(self) -> Sequence[Article]: ...

    def add_revision(self, revision: ArticleRevision) -> ArticleRevision: ...

    def get_revision(self, revision_id: str) -> ArticleRevision | None: ...

    def get_latest_revision(self, article_id: str) -> ArticleRevision | None: ...

    def list_revisions(self, article_id: str) -> Sequence[ArticleRevision]: ...

    def next_revision_number(self, article_id: str) -> int: ...

    def add_artifact(self, artifact: Artifact) -> Artifact: ...

    def get_artifact(self, artifact_id: str) -> Artifact | None: ...

    def add_workflow(self, workflow: Workflow) -> Workflow: ...

    def get_workflow(self, workflow_id: str) -> Workflow | None: ...

    def find_workflow(self, name: str, version: str) -> Workflow | None: ...

    def list_workflows(self) -> Sequence[Workflow]: ...

    def add_run(self, run: WorkflowRun) -> WorkflowRun: ...

    def update_run(self, run: WorkflowRun) -> WorkflowRun: ...

    def get_run(self, run_id: str) -> WorkflowRun | None: ...

    def find_active_run(self, article_id: str) -> WorkflowRun | None: ...

    def list_runs_by_statuses(self, statuses: Sequence[RunStatus]) -> Sequence[WorkflowRun]: ...

    def add_event(self, event: RuntimeEvent) -> RuntimeEvent: ...

    def list_events(self, run_id: str) -> Sequence[RuntimeEvent]: ...

    def add_connection(self, profile: ConnectionProfile) -> ConnectionProfile: ...

    def get_connection(self, profile_id: str) -> ConnectionProfile | None: ...

    def list_connections(self) -> Sequence[ConnectionProfile]: ...

    def add_variant(self, variant: PlatformVariant) -> PlatformVariant: ...

    def get_variant(self, variant_id: str) -> PlatformVariant | None: ...

    def list_variants_for_revision(self, revision_id: str) -> Sequence[PlatformVariant]: ...

    def add_publish_plan(self, plan: PublishPlan) -> PublishPlan: ...

    def update_publish_plan(self, plan: PublishPlan) -> PublishPlan: ...

    def get_publish_plan(self, plan_id: str) -> PublishPlan | None: ...

    def add_publish_job(self, job: PublishJob) -> PublishJob: ...

    def update_publish_job(self, job: PublishJob) -> PublishJob: ...

    def get_publish_job(self, job_id: str) -> PublishJob | None: ...

    def get_publish_job_by_idempotency(self, idempotency_key: str) -> PublishJob | None: ...

    def claim_publish_job(
        self,
        job_id: str,
        *,
        expected_states: Sequence[PublishJobState],
        claimed_state: PublishJobState,
    ) -> bool: ...

    def list_publish_jobs(self, plan_id: str) -> Sequence[PublishJob]: ...

    def list_publish_jobs_by_states(
        self,
        states: Sequence[PublishJobState],
    ) -> Sequence[PublishJob]: ...

    def add_publish_attempt(self, attempt: PublishAttempt) -> PublishAttempt: ...

    def update_publish_attempt(self, attempt: PublishAttempt) -> PublishAttempt: ...

    def next_attempt_number(self, job_id: str) -> int: ...

    def list_publish_attempts(self, job_id: str) -> Sequence[PublishAttempt]: ...

    def add_publish_receipt(self, receipt: PublishReceipt) -> PublishReceipt: ...

    def get_publish_receipt_for_job(self, job_id: str) -> PublishReceipt | None: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...
